### PR TITLE
Use current time as version in external configuration layer

### LINKED ISSUE #286: External configuration provided by `BP_TOMCAT_EXT_CONF_URI` is cached if the same image is built twice
If you provide `BP_TOMCAT_EXT_CONF_URI` to use an external configuration, the external configuration is extracted to `$CATALINA_BASE`. But when you build the image a second time and the external configuration changed, it will restore the old content instead of extracting the  external configuration again.

## Expected Behavior

The external configuration is always applied and only cached if `$BP_TOMCAT_EXT_CONF_SHA256` is provided and unchanged.

## Current Behavior

If the previous image is found, it will reuse its configuration.

## Steps to Reproduce

1. Build an image with an external configuration
```
pack build -e BP_TOMCAT_EXT_CONF_URI="https:/<redacted>.tgz" -B paketobuildpacks/builder-jammy-base  tomcat-example:issue
```

2. Check the log that the external configuration is applied

```
[builder]   Tomcat External Configuration
[builder]   Warning: Dependency has no SHA256. Skipping cache.
[builder]     Downloading from https://int.repositories.cloud.sap/artifactory/cki-generic/tomcat-configuration-sjb.tgz
[builder]     Expanding to /layers/paketo-buildpacks_apache-tomcat/catalina-base
```

3. Change the configuration and build the same tag again
```
pack build -e BP_TOMCAT_EXT_CONF_URI="https:/<redacted>.tgz" -B paketobuildpacks/builder-jammy-base  tomcat-example:issue
```

4. Check the log 
```
[builder] Paketo Buildpack for Apache Tomcat 7.9.0
[builder]   https://github.com/paketo-buildpacks/apache-tomcat
[builder]   Build Configuration:
[builder]     $BP_JAVA_APP_SERVER                                                                                                               the application server to use
[builder]     $BP_TOMCAT_CONTEXT_PATH                                                                                                           the application context path
[builder]     $BP_TOMCAT_ENV_PROPERTY_SOURCE_DISABLED  false                                                                                    Disable Tomcat's EnvironmentPropertySource
[builder]     $BP_TOMCAT_EXT_CONF_SHA256                                                                                                        the SHA256 hash of the external Tomcat configuration archive
[builder]     $BP_TOMCAT_EXT_CONF_STRIP                0                                                                                        the number of directory components to strip from the external Tomcat configuration archive
[builder]     $BP_TOMCAT_EXT_CONF_URI                  https://<redacted>.tgz  the download location of the external Tomcat configuration
[builder]     $BP_TOMCAT_EXT_CONF_VERSION                                                                                                       the version of the external Tomcat configuration
[builder]     $BP_TOMCAT_VERSION                       9.*                                                                                      the Tomcat version
[builder]   Launch Configuration:
[builder]     $BPL_TOMCAT_ACCESS_LOGGING_ENABLED                                                                                                the Tomcat access logging state
[builder]   Apache Tomcat 9.0.69: Reusing cached layer
[builder]   Launch Helper: Reusing cached layer
[builder]   Apache Tomcat Support: Reusing cached layer
[builder]   Process types:
[builder]     task:   bash catalina.sh run (direct)
[builder]     tomcat: bash catalina.sh run (direct)
[builder]     web:    bash catalina.sh run (direct)
```

## Motivations

Changing the external configuration should have an effect if rebuilding the image.

### PR DESCRIPTION
**Pull request by c0d1ngm0nk3y**
## Summary

Fixes #286 

## Use Cases

If neither `version` nor `sha` is provided, the external configuration should never be reused from layer cache since the external configuration could have changed.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by c0d1ngm0nk3y** [comment]
Any comments / feedback?

File: tomcat/build_test.go [hunk 1]
```diff
@@ -381,9 +370,22 @@ func testBuild(t *testing.T, context spec.G, it spec.S) {
 			}
 			ctx.StackID = "test-stack-id"
 
+			Expect(os.Setenv("BP_TOMCAT_EXT_CONF_SHA256", "test-sha256")).To(Succeed())
```
Comment (dmikusa) [inline tomcat/build_test.go:373]: This is minor, but I have been trying to migrate from manually calling `os.Setenv` to using `t.Setenv`. The latter will automatically clean up after the test, so it's less verbose and doesn't require manual clean up.

https://pkg.go.dev/testing#B.Setenv

If you could update the tests here to do that, it would be appreciated.

File: tomcat/build.go [hunk 2]
```diff
@@ -123,8 +124,13 @@ func (b Build) Build(context libcnb.BuildContext) (libcnb.BuildResult, error) {
...
 	var externalConfigurationDependency *libpak.BuildpackDependency
 	if uri, ok := cr.Resolve("BP_TOMCAT_EXT_CONF_URI"); ok {
-		v, _ := cr.Resolve("BP_TOMCAT_EXT_CONF_VERSION")
-		s, _ := cr.Resolve("BP_TOMCAT_EXT_CONF_SHA256")
+		v, versionExists := cr.Resolve("BP_TOMCAT_EXT_CONF_VERSION")
+		s, shaExists := cr.Resolve("BP_TOMCAT_EXT_CONF_SHA256")
+
+		if !versionExists && !shaExists {
+			v = time.Now().Format(time.RFC3339)
+			b.Logger.Infof("No BP_TOMCAT_EXT_CONF_VERSION or BP_TOMCAT_EXT_CONF_SHA256 provided, using version '%s'", v)
```
Comment (dmikusa) [inline tomcat/build.go:132]:
```suggestion
			b.Logger.Infof(color.YellowString("WARNING: No BP_TOMCAT_EXT_CONF_VERSION or BP_TOMCAT_EXT_CONF_SHA256 provided, so no layer caching will occur."))
```

I don't mind putting a timestamp in the version to force it to update, but I think we should try to make that an implementation detail and not show it to the user.

**Review by dmikusa — CHANGES_REQUESTED** [review]
A couple of minor changes. Also, GH is telling me the PR is out of date but not letting me update it. Please merge/rebase in the latest main branch.

**Review by dmikusa — APPROVED** [review]
